### ISSUE TITLE
Ban me out of discord server?

### ISSUE THREAD

**Issue by CourteousGeek** [AcidCaos/socialwarriors#1]
Your Discord rules don't state that you can't upload the latest build of social wars? I read your discord server rules and that does not apply, it is not a fair ban.

**Comment by Nerroth** [comment]
Hey.

Since this is not an issue with the project itself I will be locking this issue after answering your question.

You violated our Discord rules by posting a link to a suspicious and malicious site claiming to have a download for a newer version of this project, when in reality it was a fake installer most likely containing malware. This was brought to our attention by the community so action had to be taken. 

You also stated that this is not specifically against any rule in the Discord server but in reality this violates the Discord Guidelines instead. You're not allowed to distribute malware through Discord in any shape or form so that has been the reason of us banning you.

We do not tolerate malware being linked to or uploaded to our Discord server,.

I hope you understand the reason why you were banned.
